### ISSUE TITLE
Background issue

### ISSUE THREAD

**Issue by mytube1233** [leadscales/fragmenthud#12]
So i just renamed my file to be just "fragmenthud" and this just happen.. 
https://imgur.com/a/TglMMD8 <- link to image

**Comment by leadscales** [comment]
what file did you rename to just be "fragmenthud"? please go into more detail.

if you haven't already, please read this: https://github.com/leadscales/fragmenthud/wiki/User-Backgrounds

**Comment by mytube1233** [comment]
I renamed the file that goes into the customs folder where the rest of the mods/huds go

**Comment by leadscales** [comment]
did you try and apply a user background? i'm kinda lost here, that texture issue should only happen if you try to enable it without one created yet.

**Comment by mytube1233** [comment]
Okay, It is fixed now, i thought that would do anything else but THAT sorry for the inconvenience and also thanks for the help
