### ISSUE TITLE
???

### ISSUE THREAD

**Issue by ScriptedRoFLaN** [leadscales/fragmenthud#5]
![image](https://github.com/leadscales/fragmenthud/assets/132493843/17696aa4-f216-4992-b812-0955a63f0b8d)
no identification of on/off
![image](https://github.com/leadscales/fragmenthud/assets/132493843/998ce42c-8fd8-430c-be81-fe71e2924754)
button wents full alpha (DESIGN FLAW BTW)
![image](https://github.com/leadscales/fragmenthud/assets/132493843/16d7c7c8-1fb1-49cf-9391-65d1489f11b6)
white bit on right
![image](https://github.com/leadscales/fragmenthud/assets/132493843/5fc87731-1df4-48ee-9623-8b07012a620f)
top bar doesnt resize players properly when the server was full and went back to some players

**Comment by leadscales** [comment]
> no identification of on/off

wontfix

> button wents full alpha (DESIGN FLAW BTW)

what os are you using

> white bit on right

intentional

> top bar doesnt resize players properly when the server was full and went back to some players

wontfix and partially intentional
